services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: matvei
      POSTGRES_PASSWORD: matvei
      POSTGRES_DB: postgres
    
    ports:
      - '1488:1488'

    volumes:
      - postgres_data:/var/lib/postgres

    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network: